[tool.poetry]
name = "aic2-assignment"
version = "0.1.0"
description = ""
authors = ["agerom <agerom@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
#python = ">=3.9,<=3.13"
pandas = "^2.2.3"
holidays = "^0.60"
matplotlib = "^3.9.2"
pytest = "^8.3.3"
seaborn = "^0.13.2"
scikit-learn = "^1.5.2"
requests = "^2.12.1"
jupyter = "^1.1.1"
#keras = "^3.4.0"
#tensorflow-io-gcs-filesystem = { version = "0.37.1"}
tensorflow = "2.12"
tensorflow-io-gcs-filesystem = "0.31.0"
keras = "^2.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

#https://python-poetry.org/docs/configuration/
#poetry config --list
